# -*- coding: utf-8 -*-
"""Student_marks_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nlDzDGUCyfnKF32SlMvbCReYGH3kTUY
"""

# Student Marks Calculator

# Taking inputs
name = input("Enter student name: ")
m1 = float(input("Enter marks in Subject 1: "))
m2 = float(input("Enter marks in Subject 2: "))
m3 = float(input("Enter marks in Subject 3: "))

# Calculations
total = m1 + m2 + m3
average = total / 3

# Grade calculation
if average >= 90:
    grade = "A"
elif average >= 75:
    grade = "B"
elif average >= 60:
    grade = "C"
elif average >= 50:
    grade = "D"
else:
    grade = "F"

# Output
print("\n----- Student Report -----")
print("Name:", name)
print("Subject 1 Marks:", m1)
print("Subject 2 Marks:", m2)
print("Subject 3 Marks:", m3)
print("Total Marks:", total)
print("Average Marks:", round(average, 2))
print("Grade:", grade)